azure-pipelines.yml
azure-templates/deploy-steps.yml
azure-templates/make-build-steps.yml

Added YAML pipeline to create the DevOps project.

[#173010116] Added pipeline

---

Info/function.json
Info/handler.ts
Info/index.ts
tsconfig.json

And info endpoint we query to check downtime during swap operations.
We can remove it after the tests if needed.

Add Info function

---

openapi/ade.yaml
package.json
utils/__tests__/adeClient.test.ts
utils/adeClient.ts

Implementing the http client to interact with ADE
* I changed the spec by adding the operation id

[#173191291] ADE http client

---

models/__tests__/bonus_lease.test.ts
models/bonus_lease.ts

First implementation of `BonusLeaseModel`
* ~`familyUID` and `bonusId` fields are there just for convenience, they may be removed~
* Intended operations are just `create` and `delete` for acquire and release the lease. We might think about a more convenient interface for this kind of models

[#173285187] first implementation of lease model

---

models/__tests__/eligibility_check.test.ts
models/bonus_activation.ts
models/bonus_lease.ts
models/eligibility_check.ts
models/user_bonus.ts
package.json

@gunzip 
[here](https://github.com/pagopa/io-functions-bonus/compare/173332541-decode-on-retrieved?expand=1#diff-957931348acc316c1cf29005d0841f48R51) there's a case in which document's field are skimmed from the retrieved model

[#173332541] Decode items from db

---

DeleteEligibilityCheckActivity/handler.ts
EligibilityCheckActivity/handler.ts
EligibilityCheckOrchestrator/__tests__/index.test.ts
EligibilityCheckOrchestrator/index.ts
SendBonusActivationActivity/handler.ts
SendMessageActivity/handler.ts
SendMessageActivity/index.ts
StartBonusActivationOrchestrator/handler.ts
UpsertEligibilityCheckActivity/handler.ts
ValidateEligibilityCheckActivity/handler.ts
models/eligibility_check.ts

This implements encoding on activity call to introduce compiler time check on future input changes

[#173338092] add type validation on activity call

---

StartBonusActivation/handler.ts

[#173376411] Fix: partition key on bonus creation

---

SendBonusActivationActivity/__tests__/handler.test.ts
SendBonusActivationActivity/handler.ts
StartBonusActivationOrchestrator/handler.ts

Improve error logs for `SendBonusActivationActivity` with a more granular model

[#173376045] better logs for SendBonusActivationActivity

---

EligibilityCheck/handler.ts
EligibilityCheckActivity/handler.ts
EligibilityCheckOrchestrator/index.ts
SendBonusActivationActivity/handler.ts
StartBonusActivation/handler.ts
StartBonusActivationOrchestrator/handler.ts

Miss bonus activation (ADE) event tracking

[#173266483] Add event tracking

---

StartBonusActivation/__tests__/handler.test.ts
StartBonusActivation/handler.ts

This PR contains:
* More eloquent error handling in case of failure on lock acquire
* Fix the lock acquire as it must not result on a lock release when fail

[#173400850] Fix lock workflow

---

StartBonusActivation/__tests__/handler.test.ts
StartBonusActivation/handler.ts
StartBonusActivationOrchestrator/handler.ts
openapi/index.yaml

Needed as the mobile app needs to know the bonusId in case the bonus activation is still running (the controller returns 202)

[#173421860], [#173423382] Return the bonusID when bonus activation is running

---

StartBonusActivation/handler.ts
StartBonusActivation/models.ts
StartBonusActivation/orchestrators.ts
StartBonusActivation/utils.ts
utils/orchestrators.ts

@francescopersico FYI in case you're modifying the same files

Refactors StartBonusActivation for readability and testability

---

EligibilityCheckOrchestrator/index.ts
utils/__tests__/messages.test.ts
utils/messages.ts

Updated content messages. Now some message types accept a Date that fills the dynamic part of text.

[#173432184] - notification messages adjustments

---

utils/messages.ts

CTA inserted on notification messages for front matter purposes

[#173503595] Insert CTA on notification messages

---

StartBonusActivation/__tests__/handler.test.ts
StartBonusActivation/models.ts

I've added a check to correctly handle the case on which the lock releasing fails because it cannot find a lock. It shouldn't happen anyway.

[#173515025] added a check on lock release

---

CheckBonusProcessingActivity/__tests__/handler.test.ts
CheckBonusProcessingActivity/function.json
CheckBonusProcessingActivity/handler.ts
CheckBonusProcessingActivity/index.ts
EligibilityCheckOrchestrator/__tests__/index.test.ts
EligibilityCheckOrchestrator/index.ts
StoreFamilyUidBonusActivation/index.ts
ValidateEligibilityCheckActivity/handler.ts
utils/messages.ts

added activity for bonus_processing check before sending EligibilityCheckConflict messages

[#173432219] Send a specific message in case the bonus activation is running (or not)

---

utils/messages.ts

Copy dei messaggi aggiornati all'ultima versione del documento.
@gunzip

[#173557224] Review messages content

---

EligibilityCheckOrchestrator/__tests__/index.test.ts

Add a unit test for a scenario when all `EligibilityCheckActivity` retries fail.

Extend EligibilitycheckOrchestrator unit tests

---

StartBonusActivation/__tests__/handler.test.ts
StartBonusActivation/function.json
StartBonusActivation/handler.ts
StartBonusActivation/index.ts
StartBonusActivation/locks.ts
StartBonusActivation/models.ts
__mocks__/mocks.ts

Due to runtime issues, we swap CosmoDB's bindings with CosmoDB's client calls.
This PR is a draft as tests must be fixed

[#173810181] Removed bindings for BonusProcessing on StartBonusActivation

---

GetBonusActivation/__tests__/handler.test.ts

An an old chinese proverb says:
> More tests are better tests

More tests

---

utils/messages.ts

This PR rename every occurrence of the Payment section in Wallet in the bonus messages

[#175488816] change bonus messages
